version: "3.8"
services:
  backend:
    build: ./backend
    container_name: restaurante-backend
    ports:
      - "8080:8080"
    networks:
      - restaurante-net
  
  frontend::
    build: ./frontend
    container_name: restaurante_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - restaurante-net
    
networks:
  restaurante-net:
    driver: bridge